apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbt-docs
  namespace: dbt
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dbt-docs
  template:
    metadata:
      labels:
        app: dbt-docs
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: nginx
          image: public.ecr.aws/a5t8q4h4/dbt-docs-customer360:latest
          imagePullPolicy: "Always"
          ports:
            - name: tcp
              containerPort: 8080