
customer360:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: "{{ env_var('DBT_DEV_HOST') }}"
      port: "{{ env_var('DBT_DEV_PORT') | as_number }}"
      user: "{{ env_var('DBT_DEV_USER') }}"
      pass: "{{ env_var('DBT_DEV_PASSWORD') }}"
      dbname: "{{ env_var('DBT_DEV_DB_NAME') }}"
      schema: "{{ env_var('DBT_DEV_SCHEMA') }}"

    prod:
      type: postgres
      threads: 1
      host: "{{ env_var('DBT_DEV_HOST') }}"
      port: "{{ env_var('DBT_DEV_PORT') | as_number }}"
      user: "{{ env_var('DBT_DEV_USER') }}"
      pass: "{{ env_var('DBT_DEV_PASSWORD') }}"
      dbname: "{{ env_var('DBT_DEV_DB_NAME') }}"
      schema: "{{ env_var('DBT_DEV_SCHEMA') }}"

  target: dev