# Generated by Django 5.0.5 on 2024-05-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.TextField()),
                ('sender_account_no', models.IntegerField(verbose_name=8)),
                ('sender_bank', models.TextField()),
                ('transaction_date', models.DateField()),
                ('transaction_time', models.TimeField()),
                ('transaction_type', models.TextField()),
                ('status', models.TextField()),
                ('amount', models.IntegerField()),
                ('fee', models.FloatField(verbose_name=8)),
                ('currency', models.TextField()),
                ('description', models.TextField()),
                ('rate', models.FloatField(verbose_name=8)),
            ],
        ),
    ]
