# Generated by Django 5.0.5 on 2024-05-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender_account_no',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender_bank',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_time',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
    ]
